---
s1-ntr-vyos:
  hostname: s1-ntr-vyos
  data:
    management_interface: eth0
    management_ip: 10.100.200.240/28
  groups:
    - site1
    - vyos
s1-tr-vyos:
  hostname: s2-ntr-vyos
  data:
    management_interface: eth0
    management_ip: 10.101.200.240/28
  groups:
    - site1
    - vyos
s2-ntr-vyos:
  hostname: s2-ntr-vyos
  data:
    management_interface: eth0
    management_ip: 10.200.200.240/28
  groups:
    - site2
    - vyos
s2-tr-vyos:
  hostname: s2-tr-vyos
  data:
    management_interface: eth0
    management_ip: 10.201.200.240/28
  groups:
    - site2
    - vyos
