name: Tests
on:
  - push
  - pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
  # tests:
  #   name: Testing on Python ${{ matrix.python-version }} (${{ matrix.platform}})
  #   needs: pre-commit
  #   defaults:
  #     run:
  #       # that is to run pytest from within tests directory
  #       working-directory: tests
  #       shell: bash
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       python-version: ["3.8", "3.9", "3.10", "3.11"]
  #       platform: [ubuntu-latest]
  #   runs-on: ${{ matrix.platform }}

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup Python
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: ${{ matrix.python-version }}

  #     - name: Install Dev dependencies
  #       run: |
  #         python -m pip install poetry
  #         python -m poetry install
  #     - name: Run pytest
  #       run: python -m poetry run pytest -vv
