---
name: Tests
on:
  - push
  - pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
  implement:
    name: Testing on Python ${{ matrix.python-version }} (${{ matrix.platform}})
    needs: pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check out code repo
        uses: actions/checkout@master
        with:
          repository: orgname/reponame
          token: ${{ secrets.CODE_PAT }}
      - name: Setup Python
        uses: actions/setup-python@v3
      - name: Install Dev dependencies
        run: |
          python -m pip install poetry
          python -m poetry install -C nornir-aci
      - name: Run pytest
        run: aci_deploy -h
