---
name: Tests
on:
  - push

jobs:
  pre-commit:
    name: Check pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
  validate:
    name: Validate data
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check out code repo
        uses: actions/checkout@v3
        with:
          repository: t0m3kz/nornir-aci
          token: ${{ secrets.CODE_PAT }}
          path: nornir-aci
      - name: Setup Python
        uses: actions/setup-python@v3
      - name: Install nornir-aci
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.create false
          poetry install -C nornir-aci --without dev
      - name: Run validation
        run: |
          poetry run -C nornir-aci aci_validate -i data/lab_devices.yaml
  implement:
    name: Implement change
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check out code repo
        uses: actions/checkout@v3
        with:
          repository: t0m3kz/nornir-aci
          token: ${{ secrets.CODE_PAT }}
          path: nornir-aci
      - name: Setup Python
        uses: actions/setup-python@v3
      - name: Install nornir-aci
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.create false
          poetry install -C nornir-aci --without dev
      - name: Run impelementation
        continue-on-error: true
        id: config
        run: |
          poetry run -C nornir-aci aci_deploy -i data/lab_devices.yaml -v
          poetry run -C nornir-aci aci_deploy -i data/lab_tenants.yaml -v
      - name: Restore config
        if: ${{ failure() && steps.config.conclusion == 'failure' }}
        run: echo "restore config"
  document:
    name: Update documentation
    needs: implement
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check out code repo
        uses: actions/checkout@v3
        with:
          repository: t0m3kz/nornir-aci
          token: ${{ secrets.CODE_PAT }}
          path: nornir-aci
      - name: Setup Python
        uses: actions/setup-python@v3
      - name: Install nornir-aci
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.create false
          poetry install -C nornir-aci --without dev
      - name: Generate documentation
        run: poetry run -C nornir-aci aci_documentation -h
